sudo: false

cache:
    directories:
    - $HOME/env

language: python

notifications:
    email: false

python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    - pip install -e .

script:
    - nosetests -v -w tests/ --with-coverage --cover-erase --cover-package=entrofy

after_success:
    - coveralls
